### ISSUE TITLE
Script get killed

### ISSUE THREAD

**Issue by Horkyze** [danielegrattarola/twitter-sentiment-cnn#13]
I run a docker tensorflow/tensorflow container on my mac. 
Inside the container I followed the intructions and got to a point when I call:
```
python twitter-sentiment-cnn.py --train --save
```

However the script gets killed, with the following output:
```
root@19a3c9721bd0:/opt/twitter-cnn# python twitter-sentiment-cnn.py --train --save
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
======================= START! ========================
	data_helpers: loading positive examples...
	data_helpers: [OK]
	data_helpers: loading negative examples...
	data_helpers: [OK]
	data_helpers: cleaning strings...
	data_helpers: [OK]
	data_helpers: generating labels...
	data_helpers: [OK]
	data_helpers: concatenating labels...
	data_helpers: [OK]
	data_helpers: padding strings...
Killed
root@19a3c9721bd0:/opt/twitter-cnn#
```

Any idea what this means?

**Comment by danielegrattarola** [comment]
Most likely a memory issue, how much RAM does your computer have? Peak memory consumption on my machine is at about 7GB on Ubuntu, but I know that MacOS handles memory differently.  
Try to run the script with `--dataset_fraction 0.5` (0.5 uses half of the dataset, but it can be any number between 0. and 1.).

**Comment by Horkyze** [comment]
It has 8GB (docker only had 2GB). But I have one more machine with 16, so will try to run it there, thanks for quick reply.

**Comment by danielegrattarola** [comment]
Let me know if it works out so I can close the issue. Cheers

**Comment by Horkyze** [comment]
Yes, memory was the problem. It now works fine thanks.

btw: Is there any chance you might have the folder which describes the already trained network?
The one used here `--load path/to/ckpt/folder/`?

**Comment by danielegrattarola** [comment]
Good, I'm glad.
I don't have a trained model on my PC right now, sorry. If I'll ever have a few hours of computation to spare I'll make sure to upload a trained model to the repo. 
Cheers
