### ISSUE TITLE
Broken Load due to incorrect os.path.exists(CHECKPOINT_FILE_PATH) Assert

### ISSUE THREAD

**Issue by tzolov** [danielegrattarola/twitter-sentiment-cnn#4]
The [CHECKPOINT_FILE_PATH asserts](https://github.com/danielegrattarola/twitter-sentiment-cnn/blob/master/twitter-sentiment-cnn.py#L138) expects an exact `ckpt.ckpt` file to exist but the training produces 3 files with different suffixes: `ckpt.ckpt.meta` , `ckpt.ckpt.index` and `ckpt.ckpt.data-XXX-of-YYYY`. 
I guess the assert needs to check if files with `ckpt.ckpt` prefix exist?

**Comment by danielegrattarola** [comment]
Yes, I hadn't tested that part in the last commit. 
I removed the ```assert``` and now loading works, thanks.

Cheers, 
Daniele
