### ISSUE TITLE
can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by SamirMatkar** [danielegrattarola/twitter-sentiment-cnn#6]
Below function throws as exception "can't multiply sequence by non-int of type 'float'", any idea how to fix 

def sample_list(list, dividend):
    """
    Returns 1/dividend-th of the given list, randomply sampled. 
    """
    return random.sample(list, len(list)/dividend)

fyi: i am using python 3.5

Thanks in advance

**Comment by danielegrattarola** [comment]
Closing this because it duplicates issue https://github.com/danielegrattarola/twitter-sentiment-cnn/issues/5
