### ISSUE TITLE
  x = np.array([[vocabulary[word] for word in sentence] for sentence in sentences])  MemoryError

### ISSUE THREAD

**Issue by mrinal18** [danielegrattarola/twitter-sentiment-cnn#7]

**Comment by mrinal18** [comment]
i am getting this error: 



======================= START! ========================
        data_helpers: loading positive examples...
        data_helpers: [OK]
        data_helpers: loading negative examples...
        data_helpers: [OK]
        data_helpers: cleaning strings...
        data_helpers: [OK]
        data_helpers: generating labels...
        data_helpers: [OK]
        data_helpers: concatenating labels...
        data_helpers: [OK]
        data_helpers: padding strings...
        data_helpers: [OK]
        data_helpers: building vocabulary...
        data_helpers: [OK]
        data_helpers: building processed datasets...
Traceback (most recent call last):

  File "<ipython-input-2-471c04ad7efb>", line 1, in <module>
    runfile('/home/bizviz/Desktop/twitter-sentiment-cnn/twitter-sentiment-cnn.py', wdir='/home/bizviz/Desktop/twitter-sentiment-cnn')

  File "/home/bizviz/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/bizviz/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/bizviz/Desktop/twitter-sentiment-cnn/twitter-sentiment-cnn.py", line 150, in <module>
    x, y, vocabulary, vocabulary_inv = load_data(FLAGS.reduced_dataset)

  File "/home/bizviz/Desktop/twitter-sentiment-cnn/data_helpers.py", line 169, in load_data
    x, y = build_input_data(sentences_padded, labels, vocabulary)

  File "/home/bizviz/Desktop/twitter-sentiment-cnn/data_helpers.py", line 129, in build_input_data
    x = np.array([[vocabulary[word] for word in sentence] for sentence in sentences])

MemoryError


can someone please solve this? 
i am using anaconda3 64bit

**Comment by danielegrattarola** [comment]
Hi, 

can you give me the specs of the machine on which you are running this? 
I'd recommend at least 16GB if you are using the whole dataset, though I haven't really checked the total memory usage. 

Also, I notice that you are using Python 3: the code is for Python 2 so you might run into problems eventually.

**Comment by mrinal18** [comment]
16 gb is actually lot, maybe that's why, can you tell me how to reduce the
dataset? If possible?

Yes, I'm using python 3 and i corrected all the python 2 code.

**Comment by mrinal18** [comment]
Specs of machine: 
Memory 7.7 GiB
Processor Intel® Core™ i5-7400 CPU @ 3.00GHz × 4 
Graphics Intel® Kabylake GT2 
OS Type 64-bit
Disk 483.8 GB

**Comment by danielegrattarola** [comment]
Yes, there is a flag `--reduced_dataset` which you can use to load less samples in memory.
It's not really the best implementation, but you can load 1/100 of the dataset by setting the flag to `--reduced_dataset 100`.
The data is sampled randomly from the whole dataset, so it will still have to load all the tweets in memory at least once. I remember running it on a laptop wth 6GB of RAM, so you should be fine.

I'll change the behavior eventually, for now please use it like this.
